services:
  backend:
    build: ../cuidar_plus_api
    ports:
      - "8001:8000"
    volumes:
      - ../cuidar_plus_api:/app
  frontend:
    build:
      context: ../cuidar-plus
      dockerfile: Dockerfile
    ports:
      - "4200:80"
    depends_on:
      - backend
  app:
    build: .
    container_name: app_container
    environment:
      DATABASE_HOST: mysql
      DATABASE_PORT: 3306
      DATABASE_NAME: mydatabase
      DATABASE_USER: myuser
      DATABASE_PASSWORD: mypassword
    ports:
      - "8000:8000"
    depends_on:
      - mysql

  mysql:
    image: mysql:8.0
    container_name: mysql_container
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: mydatabase
      MYSQL_USER: myuser
      MYSQL_PASSWORD: mypassword
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data: