version: '3.8'

services:
  web:
    build: .
    container_name: cuidar_plus_web
    command: flask run --host=0.0.0.0 --port=5000
    ports:
      - "5000:5000"
    environment:
      FLASK_APP: app.py
      FLASK_ENV: development
      DB_USER: myuser
      DB_PASSWORD: mypassword
      DB_NAME: cuidar_plus_bd
      DB_HOST: postgres
    volumes:
      - .:/app
    depends_on:
      - postgres

  postgres:
    image: postgres:13
    container_name: cuidar_plus_postgres
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: cuidar_plus_bd
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    container_name: cuidar_plus_pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "8080:80"
    depends_on:
      - postgres

volumes:
  postgres_data:
