"""Configuração para PostgreSQL

Revision ID: 003e5548d766
Revises: 98f6a6113e1d
Create Date: 2025-04-04 23:44:26.153340

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '003e5548d766'
down_revision = '98f6a6113e1d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pacientes')
    with op.batch_alter_table('paciente', schema=None) as batch_op:
        batch_op.add_column(sa.Column('endereco', sa.JSON(), nullable=False))
        batch_op.alter_column('data_nascimento',
               existing_type=sa.DATE(),
               nullable=True)
        batch_op.alter_column('cpf',
               existing_type=sa.VARCHAR(length=11),
               type_=sa.String(length=14),
               nullable=True)
        batch_op.alter_column('telefone',
               existing_type=sa.VARCHAR(length=15),
               type_=sa.String(length=20),
               nullable=True)
        batch_op.alter_column('telefone_secundario',
               existing_type=sa.VARCHAR(length=15),
               type_=sa.String(length=20),
               existing_nullable=True)
        batch_op.alter_column('telefone_emergencia',
               existing_type=sa.VARCHAR(length=15),
               type_=sa.String(length=20),
               existing_nullable=True)
        batch_op.alter_column('status',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
        batch_op.alter_column('cid_primario',
               existing_type=sa.VARCHAR(length=10),
               type_=sa.String(length=20),
               nullable=True)
        batch_op.alter_column('cid_secundario',
               existing_type=sa.VARCHAR(length=10),
               type_=sa.String(length=20),
               existing_nullable=True)
        batch_op.alter_column('acomodacao',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
        batch_op.alter_column('convenio_id',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=50),
               existing_nullable=True)
        batch_op.alter_column('plano_id',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=50),
               existing_nullable=True)
        batch_op.drop_constraint('paciente_convenio_id_fkey', type_='foreignkey')
        batch_op.drop_constraint('paciente_plano_id_fkey', type_='foreignkey')
        batch_op.drop_column('endereco_json')


        op.create_table('paciente')
        

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('paciente', schema=None) as batch_op:
        batch_op.add_column(sa.Column('endereco_json', sa.TEXT(), autoincrement=False, nullable=True))
        batch_op.create_foreign_key('paciente_plano_id_fkey', 'plano', ['plano_id'], ['id'], ondelete='SET NULL')
        batch_op.create_foreign_key('paciente_convenio_id_fkey', 'convenio', ['convenio_id'], ['id'], ondelete='SET NULL')
        batch_op.alter_column('plano_id',
               existing_type=sa.String(length=50),
               type_=sa.INTEGER(),
               existing_nullable=True)
        batch_op.alter_column('convenio_id',
               existing_type=sa.String(length=50),
               type_=sa.INTEGER(),
               existing_nullable=True)
        batch_op.alter_column('acomodacao',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
        batch_op.alter_column('cid_secundario',
               existing_type=sa.String(length=20),
               type_=sa.VARCHAR(length=10),
               existing_nullable=True)
        batch_op.alter_column('cid_primario',
               existing_type=sa.String(length=20),
               type_=sa.VARCHAR(length=10),
               nullable=False)
        batch_op.alter_column('status',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
        batch_op.alter_column('telefone_emergencia',
               existing_type=sa.String(length=20),
               type_=sa.VARCHAR(length=15),
               existing_nullable=True)
        batch_op.alter_column('telefone_secundario',
               existing_type=sa.String(length=20),
               type_=sa.VARCHAR(length=15),
               existing_nullable=True)
        batch_op.alter_column('telefone',
               existing_type=sa.String(length=20),
               type_=sa.VARCHAR(length=15),
               nullable=False)
        batch_op.alter_column('cpf',
               existing_type=sa.String(length=14),
               type_=sa.VARCHAR(length=11),
               nullable=False)
        batch_op.alter_column('data_nascimento',
               existing_type=sa.DATE(),
               nullable=False)
        batch_op.drop_column('endereco')

    op.create_table('paciente',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('nome_completo', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('data_nascimento', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('cpf', sa.VARCHAR(length=14), autoincrement=False, nullable=True),
    sa.Column('genero', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('estado_civil', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('profissao', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('nacionalidade', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('endereco', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('telefone', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('telefone_secundario', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('email', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('contato_emergencia', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('telefone_emergencia', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('cid_primario', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('cid_secundario', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('acomodacao', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('medico_responsavel', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('alergias', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('case_responsavel', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('convenio_id', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('plano_id', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('numero_carteirinha', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('data_validade', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='pacientes_pkey'),
    sa.UniqueConstraint('cpf', name='pacientes_cpf_key')
    )
    # ### end Alembic commands ###
