"""Move tipo_contratacao and conselho_profissional to User

Revision ID: 453d521fbd5a
Revises: b77929510cbe
Create Date: 2025-04-09 00:46:39.737041

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '453d521fbd5a'
down_revision = 'b77929510cbe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('funcoes', schema=None) as batch_op:
        batch_op.drop_column('conselho_profissional')
        batch_op.drop_column('tipo_contratacao')

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('conselho_profissional', sa.String(length=50), nullable=True))
        batch_op.alter_column('tipo_contratacao',
               existing_type=mysql.VARCHAR(length=30),
               type_=sa.Enum('c', 't', 'p'),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('tipo_contratacao',
               existing_type=sa.Enum('c', 't', 'p'),
               type_=mysql.VARCHAR(length=30),
               existing_nullable=True)
        batch_op.drop_column('conselho_profissional')

    with op.batch_alter_table('funcoes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tipo_contratacao', mysql.ENUM('c', 't', 'p'), nullable=False))
        batch_op.add_column(sa.Column('conselho_profissional', mysql.VARCHAR(length=50), nullable=True))

    # ### end Alembic commands ###
