"""Adicionar campos de contato e responsáveis ao modelo Paciente

Revision ID: 4f24033e0846
Revises: d96bc6a31379
Create Date: 2025-03-22 14:23:03.698827

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4f24033e0846'
down_revision = 'd96bc6a31379'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('acompanhamentos', schema=None) as batch_op:
        batch_op.drop_constraint('fk_acompanhamentos_user', type_='foreignkey')
        batch_op.drop_constraint('fk_acompanhamentos_paciente', type_='foreignkey')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('acompanhamentos', schema=None) as batch_op:
        batch_op.create_foreign_key('fk_acompanhamentos_paciente', 'paciente', ['paciente_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
        batch_op.create_foreign_key('fk_acompanhamentos_user', 'user', ['usuario_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')

    # ### end Alembic commands ###
