"""substituir_e_adicionar_campos_paciente

Revision ID: 7f57232606b9
Revises: 4f24033e0846
Create Date: 2025-03-23 19:00:12.710874

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '7f57232606b9'
down_revision = '4f24033e0846'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('paciente', schema=None) as batch_op:
        batch_op.add_column(sa.Column('convenio_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('numero_carteirinha', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('telefone_secundario', sa.String(length=15), nullable=True))
        batch_op.add_column(sa.Column('genero', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('estado_civil', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('profissao', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('nacionalidade', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('plano_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('data_validade', sa.Date(), nullable=True))
        batch_op.drop_column('identificador_prestadora')
        batch_op.drop_column('operadora')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('paciente', schema=None) as batch_op:
        batch_op.add_column(sa.Column('operadora', mysql.VARCHAR(length=50), nullable=False))
        batch_op.add_column(sa.Column('identificador_prestadora', mysql.VARCHAR(length=50), nullable=False))
        batch_op.drop_column('data_validade')
        batch_op.drop_column('plano_id')
        batch_op.drop_column('nacionalidade')
        batch_op.drop_column('profissao')
        batch_op.drop_column('estado_civil')
        batch_op.drop_column('genero')
        batch_op.drop_column('telefone_secundario')
        batch_op.drop_column('numero_carteirinha')
        batch_op.drop_column('convenio_id')

    

    # ### end Alembic commands ###
