"""ajuste campo tipo contratacao

Revision ID: 8c5bce54556f
Revises: d0a85ad274a3
Create Date: 2025-04-08 20:44:45.392912

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '8c5bce54556f'
down_revision = 'd0a85ad274a3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('tipo_contratacao',
               existing_type=mysql.VARCHAR(length=1),
               type_=sa.String(length=30),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('tipo_contratacao',
               existing_type=sa.String(length=30),
               type_=mysql.VARCHAR(length=1),
               existing_nullable=True)

    # ### end Alembic commands ###
