"""remove tabela acompanhamentos

Revision ID: 98f6a6113e1d
Revises: 7f57232606b9
Create Date: 2025-04-02 14:27:12.627851

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '98f6a6113e1d'
down_revision = '7f57232606b9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('acompanhamentos')
    op.drop_table('tratamento')
    with op.batch_alter_table('paciente', schema=None) as batch_op:
        batch_op.add_column(sa.Column('endereco_json', sa.Text(), nullable=True))
        batch_op.create_foreign_key(None, 'plano', ['plano_id'], ['id'], ondelete='SET NULL')
        batch_op.create_foreign_key(None, 'convenio', ['convenio_id'], ['id'], ondelete='SET NULL')
        batch_op.drop_column('numero')
        batch_op.drop_column('rua')
        batch_op.drop_column('cep')
        batch_op.drop_column('complemento')
        batch_op.drop_column('bairro')
        batch_op.drop_column('cidade')
        batch_op.drop_column('estado')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('paciente', schema=None) as batch_op:
        batch_op.add_column(sa.Column('estado', mysql.VARCHAR(length=2), nullable=False))
        batch_op.add_column(sa.Column('cidade', mysql.VARCHAR(length=50), nullable=False))
        batch_op.add_column(sa.Column('bairro', mysql.VARCHAR(length=50), nullable=False))
        batch_op.add_column(sa.Column('complemento', mysql.VARCHAR(length=50), nullable=True))
        batch_op.add_column(sa.Column('cep', mysql.VARCHAR(length=8), nullable=False))
        batch_op.add_column(sa.Column('rua', mysql.VARCHAR(length=100), nullable=True))
        batch_op.add_column(sa.Column('numero', mysql.VARCHAR(length=10), nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('endereco_json')

    op.create_table('tratamento',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('paciente_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('medicamento', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('posologia', mysql.VARCHAR(length=200), nullable=False),
    sa.Column('frequencia', mysql.VARCHAR(length=50), nullable=False),
    sa.Column('duracao', mysql.VARCHAR(length=50), nullable=False),
    sa.Column('data_inicio', sa.DATE(), nullable=False),
    sa.Column('data_fim', sa.DATE(), nullable=True),
    sa.Column('observacoes', mysql.TEXT(), nullable=True),
    sa.Column('status', mysql.VARCHAR(length=20), nullable=False),
    sa.Column('created_at', mysql.DATETIME(), nullable=True),
    sa.Column('updated_at', mysql.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['paciente_id'], ['paciente.id'], name='tratamento_ibfk_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('acompanhamentos',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('descricao', mysql.TEXT(), nullable=False),
    sa.Column('data_criacao', mysql.DATETIME(), nullable=True),
    sa.Column('paciente_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('usuario_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['paciente_id'], ['paciente.id'], name='acompanhamentos_ibfk_1'),
    sa.ForeignKeyConstraint(['usuario_id'], ['user.id'], name='acompanhamentos_ibfk_2'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
