"""Move tipo_contratacao and conselho_profissional to User

Revision ID: aa1aeb053428
Revises: 453d521fbd5a
Create Date: 2025-04-09 00:48:35.668008

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'aa1aeb053428'
down_revision = '453d521fbd5a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('tipo_contratacao',
               existing_type=mysql.VARCHAR(length=30),
               type_=sa.Enum('c', 't', 'p'),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('tipo_contratacao',
               existing_type=sa.Enum('c', 't', 'p'),
               type_=mysql.VARCHAR(length=30),
               existing_nullable=True)

    # ### end Alembic commands ###
