"""empty message

Revision ID: b77929510cbe
Revises: 07547fa75f00
Create Date: 2025-04-08 20:47:36.678974

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'b77929510cbe'
down_revision = '07547fa75f00'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('tipo_contratacao',
               existing_type=mysql.VARCHAR(length=1),
               type_=sa.String(length=30),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('tipo_contratacao',
               existing_type=sa.String(length=30),
               type_=mysql.VARCHAR(length=1),
               existing_nullable=True)

    # ### end Alembic commands ###
