"""Atualiza o modelo Paciente

Revision ID: c934671afabd
Revises: 
Create Date: 2025-03-06 17:31:48.549555

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c934671afabd'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('paciente', schema=None) as batch_op:
        batch_op.add_column(sa.Column('identificador_prestadora', sa.String(length=50), nullable=False))
        batch_op.add_column(sa.Column('acomodacao', sa.String(length=50), nullable=False))
        batch_op.add_column(sa.Column('telefone', sa.String(length=15), nullable=False))
        batch_op.add_column(sa.Column('alergias', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('cid_secundario', sa.String(length=10), nullable=True))
        batch_op.add_column(sa.Column('data_nascimento', sa.Date(), nullable=False))
        batch_op.add_column(sa.Column('bairro', sa.String(length=50), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('paciente', schema=None) as batch_op:
        batch_op.drop_column('bairro')
        batch_op.drop_column('data_nascimento')
        batch_op.drop_column('cid_secundario')
        batch_op.drop_column('alergias')
        batch_op.drop_column('telefone')
        batch_op.drop_column('acomodacao')
        batch_op.drop_column('identificador_prestadora')

    # ### end Alembic commands ###
