"""adicionar coluna tipo_contratacao

Revision ID: d0a85ad274a3
Revises: f9d0356b6663
Create Date: 2025-04-08 20:24:34.438050

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd0a85ad274a3'
down_revision = 'f9d0356b6663'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tipo_contratacao', sa.String(length=1), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('tipo_contratacao')

    # ### end Alembic commands ###
