"""Adicionar campo cep separado do endereco

Revision ID: f9d0356b6663
Revises: dbb98b0044bf
Create Date: 2025-04-08 02:31:09.716632

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f9d0356b6663'
down_revision = 'dbb98b0044bf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cep', sa.String(length=10), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('cep')

    # ### end Alembic commands ###
